---
title: "Curriculum Vitae"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

****


> [Download CV](CVE.pdf)\


****

##### Current Position

<font size="4">
· Associate Professor of Economics (with Tenure), Universidad Pública de Navarra (UPNA), Pamplona, Spain, 2023/02--present.\
· Member of the Institute for Advanced Research in Business and Economics (INARBE), Universidad Pública de Navarra (UPNA) Pamplona, Spain, 2021/06--present.\

****

##### Previous Positions

· Visiting researcher, Departament of Economics, WU Vienna University of Economics and Business, Vienna, Austria, 2022/09--2023/08.

· Assistant Professor, Department of Economics, Universidad Pública de Navarra, Pamplona (UPNA), Spain, 2018/11--2023/01.\

· Researcher, Instituto Flores de Lemus, Department of Statistics, Universidad Carlos III de Madrid, Spain, 2006/10--2014/03.\

· Assistant Researcher, Instituto Flores de Lemus, Department of Statistics, Universidad Carlos III de Madrid, Spain, 2002/12--2006/10.\

· Researcher, Centro de Investigaciones para el Desarrollo, Department of Economics, Universidad Nacional de Colombia, Bogotá, 1997/09--2000/08.\

· Lecturer, Department of Economics, Universidad Nacional de Colombia, Bogotá, 1997/08--1999/11.

****

##### Education

· Ph.D. in Economics, Universidad de Salamanca, Spain, 2016.\
&emsp;&emsp; Outstanding doctorate award, summa cum laude.\
&emsp;&emsp; Dissertation: Three Essays on Applied Time Series Econometrics.\
&emsp;&emsp; Advisor: Rebeca Jiménez-Rodríguez.\
&emsp;&emsp; Committee: Dolores Gadea (chair), Marcelo Sánchez, Gabriel Pérez Quirós.

· M.A. in Economics (Doctoral Studies, D.E.A.), Universidad de Alcalá, Spain, 2002.

· M.A. in Economics, Universidad Nacional de Colombia, 1995.

· B.A. in Economics, Universidad Nacional de Colombia, 1995.

· B.Sc. in Forest Engineering, Universidad Distrital, Colombia, 1993.

****

##### Research Interests

Time Series Econometrics, Empirical Macroeconomics, Energy Economics.

****

##### Conference and Seminar Presentations

· Workshop on Energy Policy, Castelló de la Plana, Spain, 2023.

· WU Department of Economics-National Bank of Slovakia: Internal Economic Research Seminar, Bratislava, Slovakia, 2023.

· XI Meeting on International Economics, Castelló de la Plana, Spain, 2023.

· 44th Symposium Spanish Economic Association (SAEe), Alicante, Spain, 2019.

· II Workshop of the Spanish Macroeconomics Network, Barcelona, Spain, 2019.

· XX Conference on International Economics, Granada, Spain, 2019.

· Department of Economics, Universidad de Malaga, Spain, 2018.

· Department of Economics, Universidad Autónoma de Madrid, Spain, 2017.

· 12th Conference of the Spanish Association for Energy Economics, Salamanca, Spain, 2017.

· 7th Research Workshop on Energy Markets, Valencia, Spain, 2016.

· Energy Economics Iberian Conference, Lisboa, Portugal, 2016.

· 32nd International Symposium on Forecasting, Boston, U.S.A., 2012.

· XXXIII Congreso Nacional de Estadística e Investigación Operativa, Madrid, Spain, 2012.

· Association of Southern European Economic Theorists, Universidad de Évora, Portugal, 2011.

· Euro-Mediterranean Competitiveness Meeting, Universidad de Alcalá, Spain, 2011.

****

##### Referee Activity

Economic Modelling | Energy Economics | Energy Sources, Part B: Economics, Planning, and Policy | The Energy Journal | The World Economy

****

##### Teaching

Universidad Pública de Navarra (UPNA):

· Economics of the European Union, (UG), 2024.

· Introduction to Economics, (UG), 2019--2023.

· Industrial Organization, (UG), 2019--2021.

· Microeconomics, (UG), 2019--2020.

\
Universidad Nacional de Colombia:

· Macroeconomics, (UG, PG), 1997--1999.

****

##### Awards and distinctions

· Accredited for Associate Professor by the Ministry of Universities in Spain, 2021.

· Accredited for Assistant Professor by the Ministry of Universities in Spain, 2017.

· Universidad de Salamanca, Outstanding Doctorate Award, 2016.

· Santander Bank - Universidad de Alcalá, Scholarship, 2000.

· Inter-American Development Bank (IDB). Invited to the Youth and Growth Forum, Jerusalem, Israel, 1995.

<br>