\documentclass[11pt]{article} % Font size - 10pt, 11pt or 12pt
\usepackage[hmargin=3cm, vmargin=2.5cm]{geometry} % Document margins
\usepackage{marvosym} % Required for symbols in the colored box
\usepackage{ifsym} % Required for symbols in the colored box
\usepackage[usenames,dvipsnames]{xcolor} % Allows the definition of hex colors

% Colors for links, text and headings
%-----------------------------------------------------------------------
\usepackage{hyperref}
\definecolor{linkcolor}{HTML}{506266} % Blue-gray color for links
\definecolor{shade}{HTML}{F0F6F7} % Peach color for the contact information box
\definecolor{text1}{HTML}{62797B} % Main document font color, off-black
\definecolor{headings}{HTML}{000066} % Dark red color for headings
% Other color palettes: shade=B9D7D9 and linkcolor=A40000; shade=D4D7FE and linkcolor=FF0080

\hypersetup{colorlinks,breaklinks, urlcolor=linkcolor, linkcolor=linkcolor} % Set up links and colors

\renewcommand{\headrulewidth}{1pt} % Get rid of the default rule in the header

\usepackage{titlesec} % Allows creating custom \section's

% Format of the section titles
\titleformat{\section}{\color{headings}
\scshape\large\raggedright}{}{0em}{}[\color{black}\titlerule]
\titlespacing{\section}{0pt}{0pt}{5pt} % Spacing around titles
\usepackage[T1]{fontenc} 
\usepackage[utf8]{inputenc}
\usepackage[spanish]{babel}
\usepackage{enumitem}
\usepackage{datetime}
\setlength{\itemsep}{0.4cm} 
\newdateformat{mydate}{\monthname[\THEMONTH] \THEYEAR}

%=============================HEADERS AND FOOTERS=============================
\usepackage{fancyhdr}							          % Custom headers\pagestyle{fancy}		  					            
\pagestyle{fancy}
\usepackage{lastpage}	                      % page number
\lhead{}                                    % Header: left side empty
\chead{}                                    % Header: center side empty
\rhead{}                                    % Header: rigth side empty
\lfoot{\footnotesize César Castro Rozo}   % Footer: left side
\cfoot{\footnotesize December, 2025}                                    % Footer: center side empty
\rfoot{\footnotesize\thepage}	% "Page 1 of 2"

% \renewcommand{\footrulewidth}{0.1pt}        % Footer: line
\fancypagestyle{firststyle}{\fancyhf{} \fancyfoot[R]{\footnotesize Página \thepage\ de \pageref{LastPage}} }
%============================================================================

\setlength{\parskip}{1em}            % paragraph separation
\onehalfspacing
\begin{document}

\par{\centering{\color{black}{\sffamily\Huge César Castro Rozo}\\
\vspace{5pt}
{\color{headings} \scshape{Curriculum vitae}}\\
\vspace{5pt}
{\color{headings} \scshape{December, 2025}}\\
\vspace{10pt}}

\colorbox{shade}{{
\begin{tabular}{c|p{8cm}}

{\textifsymbol{18}} & Universidad Pública de Navarra\\
& \href{https://www.unavarra.es/en/sites/departamentos/economia.html}{Department of Economics}\\
& Campus Arrosadia, Madroño Building\\
\vspace{5pt}\raisebox{-4pt} & Pamplona, Spain, 31006\\
\vspace{5pt}\raisebox{-4pt}{\Telefon} & Phone: (+34) 948 16 93 60\\
\vspace{5pt}\raisebox{-4pt}{\Letter} & Email: \href{mailto:cesar.castro@unavarra.es}{cesar.castro@unavarra.es} \\
\vspace{5pt}\raisebox{-4pt}{\Mundus} & Homepage: \href{https://cecarozo.github.io/cesar.castro}{https://cecarozo.github.io/cesar.castro}\\
\end{tabular}
}
}
\vspace{15pt}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Current Position} 
\begin{itemize}
  \item\textbf{Associate Professor of Economics (with tenure)}, Universidad Pública de Navarra\\ (UPNA), Pamplona, Spain, 2025/01--present.\\
  \item\textbf{Member} of the Institute for Advanced Research in Business and Economics (INARBE), Universidad Pública de Navarra (UPNA), Pamplona, Spain, 2021/06--present.
\end{itemize}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Previous Positions} 
\begin{itemize}
  \item\textbf{Associate Professor of Economics}, Universidad Pública de Navarra\\ (UPNA), Pamplona, Spain, 2023/02--2025/01.\\
  \item\textbf{Visiting researcher}, Department of Economics, WU Vienna University of Economics and Business, Vienna, Austria, 2022/09--2023/08.\\
  \item\textbf{Assistant Professor of Economics}, Universidad Pública de Navarra\\ (UPNA), Pamplona, Spain, 2018/11--2023/01.
  \item \textbf{Researcher}, Instituto Flores de Lemus, Department of Statistics, Universidad Carlos III de Madrid, Spain, 2006/10--2014/03.
  \item \textbf{Assistant Researcher}, Instituto Flores de Lemus, Department of Statistics, Universidad Carlos III de Madrid, Spain, 2002/12--2006/10.
  \item \textbf{Researcher}, Centro de Investigaciones para el Desarrollo, Department of Economics, Universidad Nacional de Colombia, Bogotá, 1997/09--2000/08.
  \item \textbf{Lecturer}, Department of Economics, Universidad Nacional de Colombia, Bogotá, 1997/08--1999/11.
\end{itemize}

\vspace{15pt}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Education}
\begin{itemize}
  \item {\textbf{Ph.D. in Economics}, Universidad de Salamanca, Spain.\\
  Outstanding Doctorate Award, summa cum laude.\\
  Dissertation title: \emph{Three Essays on Applied Time Series Econometrics}.\\
  Advisor: Rebeca Jiménez-Rodríguez.\\
  Committee: Dolores Gadea (chair), Marcelo Sánchez, Gabriel Pérez Quirós.}
  \item \textbf{M.A. in Economics (Doctoral Studies, D.E.A.)}, Universidad de Alcalá, Spain.
  \item \textbf{M.A. in Economics}, Universidad Nacional de Colombia.
  \item \textbf{B.A. in Economics}, Universidad Nacional de Colombia.
  \item \textbf{B.Sc. in Forest Engineering}, Universidad Distrital, Colombia.
\end{itemize}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Research Interests}
Time Series Econometrics, Empirical Macroeconomics, Energy Economics.\\

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Papers in refereed journals}
\begin{itemize}

  \item \textbf{``The pass-through of energy commodity price volatility along the  pricing chain in the euro area: A disaggregate approach''} with Jiménez-Rodríguez, R. (Universidad de Salamanca). \emph{International Review of Economics and Finance}, 104, 104733, 2025.

  \item \textbf{``The impact of oil shocks on the stock market''} with Jiménez-Rodríguez, R. (Universidad de Salamanca). \emph{Global Finance Journal}, 60, 100967, 2024.

  \item \textbf{``Oil price pass-through into inflation in Spain at national and regional level''} with L. Topan (Universidad Complutense de Madrid), A. Barge-Gil (Universidad Complutense de Madrid), and M. Jerez (Universidad Complutense de Madrid). \emph{SERIEs}, 11(3), September 2020.

  \item \textbf{``Dynamic interactions between oil price and exchange rate''} with R. Jiménez-Rodríguez (Universidad de Salamanca). \emph{PLoS ONE}, 15(8), August 2020,  e0237172.

  \item \textbf{``Oil price pass-through along the price chain in the euro area''} with R. Jiménez-Rodríguez (Universidad de Salamanca). \emph{Energy Economics}, 64, May 2017, 24--30.

  \item \textbf{``A new look at oil price pass-through into inflation: Evidence from disaggregated European data''} with R. Jiménez-Rodríguez (Universidad de Salamanca), P. Poncela (JRC, European Commission), and E. Senra (Universidad de Alcalá). \emph{Economia Politica: Journal of Analytical and Institutional Economics}, 34(1), December 2016, 55--82.

  \item \textbf{``The deflationary effect of oil prices in the euro area''} with A. Barge-Gil (Universidad Complutense de Madrid), and M. Jerez (Universidad Complutense de Madrid). \emph{Energy Economics}, 56, May 2016, 389--397.
\end{itemize}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Other publications}
\begin{itemize}
\item \textbf{``Oil Prices and Inflation in the Euro Area and its Main Countries: Germany, France, Italy and Spain''} with P. Poncela (Universidad Autónoma de Madrid) and E. Senra (Universidad de Alcalá). \emph{FUNCAS Working papers series}, 701, December 2012.

  \item \textbf{``Do we see the effects of oil variations in official statistics price data?''} with P. Poncela (Universidad Autónoma de Madrid), and E. Senra (Universidad de Alcalá). \emph{Boletín de Estadística e Investigación Operativa}, 27, February 2011, 29--41.

  \item \textbf{``El diferencial de inflación en los servicios entre España y la euro área''} with E. Carluccio (Universidad Carlos III de Madrid). \emph{Papeles de Economía Española}, 120, June 2009, 69--89.

  \item \textbf{``Mercado de crédito 1990-1999. La factura de cobro del financiamiento''} with J. Espitia (General Controller of Colombia), and J. Villamizar (General Controller of Colombia). \emph{Gestión Fiscal}, 8, 2000, 6--33.

  \item \textbf{``La demanda de lotería y juegos de azar''} with J.I. González (Universidad Nacional de Colombia). \emph{INNOVAR, Revista de Ciencias Administrativas y Sociales}, 16, December 2000, 27--48.}
\end{itemize}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Work in Progress}
\begin{itemize}
\item \textbf{``Expectations in the Global Market of Crude Oil''} 
\item \textbf{``The Pass-Through of Oil Price Volatility to Macroeconomic Variables in the Euro Area''} (with Rebeca Jiménez-Rodríguez)
\end{itemize}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Research Projects}
\begin{itemize}
  \item \textbf{New developments in economic modelling: Mechanisms, causality and institutional analysis.} Project leader: Javier Hualde--Jorge Alcalde. Research funding: Spanish Ministry of Science PID2021-127119NB-100. Spain, 2022--present.
  \item \textbf{Design and application of economic models for institutional analysis.} Project leader: José E. Galdón. Research funding: Spanish Comission of Science PCG2018-093542-B-100. Spain, 2019--2022.
  \item \textbf{Dynamic econometric models, forecasts, economic outlook, inflation, macroeconomic models and time series.} Project leader: Antoni Espasa. Research funding: Universidad Carlos III de Madrid. Spain, 2010--2014.
  \item \textbf{Forecast and macroeconomic analysis. Inflation and relative prices in the region of Andalusia, Spain.} Project leader: Antoni Espasa. Research funding: Government of Andalusia. Spain, 2007--2009.
  \item \textbf{Analysis and forecasts of inflation.} Project leader: Antoni Espasa. Research funding: Universidad Carlos III de Madrid. Spain, 2006--2007.
  \item \textbf{Analysis and forecasts of inflation in the region of Madrid, Spain.} Project leader: Antoni Espasa. Research funding: Government of Madrid and Caja Madrid. Spain, 2002--2006.
  \item \textbf{Lottery demand.} Project leader: Jorge Iván González. Research funding: Lottery of Bogota. Colombia, 1999--2000.
  \item \textbf{Development plan in the region of Guavio, Colombia.} Project leader: César Castro. Research funding: Regional environment corporation, CORPOGUAVIO. Colombia, 1999--2000.
  \item \textbf{Environmental management in Colombian environmental ministry.} Project leader: César Castro. Research funding: Environmental ministry of Colombia. Colombia, 1999.
  \item \textbf{Economic impact of logging in indigenous area.} Project leader: César Castro. Research funding: Regional environment corporation, CODECHOCO. Colombia, 1997--1999.
\end{itemize}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Conference and Seminar Presentations} 
\begin{itemize}
  \item \textbf{2023}\\
  Workshop on Energy Policy, Castelló de la Plana, Spain.\\
  WU Department of Economics-National Bank of Slovakia: Internal Economic Research Seminar, Bratislava, Slovakia.\\
  XI Meeting on International Economics, Castelló de la Plana, Spain.
  \item \textbf{2019}\\
  44th Symposium Spanish Economic Association (SAEe), Alicante, Spain.\\
  II Workshop of the Spanish Macroeconomics Network, Barcelona, Spain.\\
  XX Conference on International Economics, Granada, Spain.
  \item \textbf{2018}\\
  Department of Economics, Universidad de Malaga, Spain.
  \item \textbf{2017}\\
  Department of Economics, Universidad Autónoma de Madrid, Spain.\\
  12th Conference of the Spanish Association for Energy Economics, Salamanca, Spain.
  \item \textbf{2016}\\
  7th Research Workshop on Energy Markets, Universidad de Valencia, Spain.\\
  Energy Economics Iberian Conference, Lisboa, Portugal.
  \item \textbf{2012} 32nd International Symposium on Forecasting, Boston, U.S.A.\\
  XXXIII Congreso Nacional de Estadística e Investigación Operativa, Madrid, Spain.
  \item \textbf{2011} Association of Southern European Economic Theorists, Évora, Portugal.\\
  Euro-Mediterranean Competitiveness Meeting, Universidad de Alcalá, Spain.
\end{itemize}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Referee Activity}
\raggedright
Economic Modelling | Energy Economics | Energy Sources, Part B: Economics, Planning, and Policy | The Energy Journal | The World Economy\\

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Teaching experience} 
\begin{itemize}
  \item Universidad Pública de Navarra (UPNA):
  \begin{itemize}
    \item Development Economics (UG), 2024
    \item Economics of the European Union (UG), 2024
    \item Introduction to Economics (UG), 2019--2025
    \item Industrial Organization (UG), 2019--2021
    \item International Trade (UG), 2024
    \item Macroeconomics (UG), 2024--2025
    \item Microeconomics (UG), 2019--2020
  \end{itemize}
  \item Universidad Nacional de Colombia:\\
  Macroeconomics (UG, PG) , 1997--1999.
\end{itemize}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Awards and distinctions} 
\begin{itemize}
  \item Positive evaluation for Associate Professor by ANECA (``Profesor Titular de Universidad'') Spain, 2025.
  \item Positive evaluation for Associate Professor by ANECA (``Profesor Contratado Doctor'') Spain, 2021.
  \item Positive evaluation for Assistant Professor by ANECA (``Profesor Ayudante Doctor'') Spain, 2017.
  \item Outstanding Doctorate Award, Universidad de Salamanca, 2016.
  \item Santander Bank--Universidad de Alcalá, Scholarship, 2000.
  \item Inter-American Development Bank (IDB), Invited to the Youth and Growth Forum, Jerusalem, Israel, 1995.
\end{itemize}

\end{document}