\documentclass[11pt]{article} % Font size - 10pt, 11pt or 12pt
\usepackage[hmargin=3cm, vmargin=2.5cm]{geometry} % Document margins
\usepackage{marvosym} % Required for symbols in the colored box
\usepackage{ifsym} % Required for symbols in the colored box
\usepackage[usenames,dvipsnames]{xcolor} % Allows the definition of hex colors

% Colors for links, text and headings
%-----------------------------------------------------------------------
\usepackage{hyperref}
\definecolor{linkcolor}{HTML}{506266} % Blue-gray color for links
\definecolor{shade}{HTML}{F0F6F7} % Peach color for the contact information box
\definecolor{text1}{HTML}{62797B} % Main document font color, off-black
\definecolor{headings}{HTML}{000066} % Dark red color for headings
% Other color palettes: shade=B9D7D9 and linkcolor=A40000; shade=D4D7FE and linkcolor=FF0080

\hypersetup{colorlinks,breaklinks, urlcolor=linkcolor, linkcolor=linkcolor} % Set up links and colors

\renewcommand{\headrulewidth}{0pt} % Get rid of the default rule in the header

\usepackage{titlesec} % Allows creating custom \section's

% Format of the section titles
\titleformat{\section}{\color{headings}
\scshape\large\raggedright}{}{0em}{}[\color{black}\titlerule]
\titlespacing{\section}{0pt}{0pt}{5pt} % Spacing around titles
\usepackage[spanish]{babel}
\usepackage[utf8]{inputenc}
\usepackage{enumitem}
\usepackage{datetime}
\setlength{\itemsep}{0.4cm} 
\newdateformat{mydate}{\monthname[\THEMONTH] \THEYEAR}

\setlength{\parskip}{1em}            % paragraph separation
\onehalfspacing
\begin{document}

\par{\centering{\sffamily\Huge César Castro Rozo}\\
\vspace{5pt}
{\color{headings} \scshape{May, 2017}}\\
\vspace{10pt}}

\colorbox{shade}{{
\begin{tabular}{c|p{13cm}}
\vspace{5pt}\raisebox{-4pt}{\textifsymbol{18}} & Calle Cipriano Sancho, 36, 4-A, Madrid, 28017, Spain\\
\vspace{5pt}\raisebox{-4pt}{\Mobilefone} & +34 679 54 82 37\\
\vspace{5pt}\raisebox{-4pt}{\Letter} & email: \href{mailto:castrorozo@gmail.com}{ccastrorozo@gmail.com} \\
\vspace{5pt}\raisebox{-4pt}{\Aquarius} & Nationality: Colombia - Spain\\
\vspace{5pt}\raisebox{-4pt}{\Mundus} & www: \href{https://cecarozo.github.io/cesar.castro}{https://cecarozo.github.io/cesar.castro}\\
\end{tabular}
}
}\\[10pt]

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\section{Education} 

\begin{tabular}{rl{-2cm}} % Start a table with two columns, one for dates and one for qualifications

2016 & \textbf{Ph.D.}, Economics (Summa cum laude), Universidad de Salamanca.\\
\vspace{1pt}& Outstanding Doctorate Award, 2016.\\
\vspace{1pt}& Dissertation title: Three Essays on Applied Time Series Econometrics.\\
\vspace{1pt}& Advisor: Rebeca Jiménez-Rodríguez.\\
\vspace{5pt}& Committee: Dolores Gadea (chair), Marcelo Sánchez, Gabriel Pérez Quirós.\\

\vspace{5pt}2002 & \textbf{D.E.A.} (Doctoral Studies), Economics, Universidad de Alcalá.\\

\vspace{5pt}2000 & \textbf{M.A.}, Economics, Universidad Nacional de Colombia.\\

1995 & \textbf{B.A.}, Economics, Universidad Nacional de Colombia.\\
\vspace{5pt}& (Approved spanish equivalent B.A.)\\

1993 & \textbf{B.Sc.}, Forestry Engineering, Universidad Distrital, Bogotá, Colombia.\\

\end{tabular}
\vspace{10pt}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Research Interests}

Time Series Econometrics, Empirical Macroeconomics, Energy Economics.
\vspace{10pt}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\section{Publications}

\begin{enumerate}

\item \textbf{``Oil price pass-through along the price chain in the euro area.''} Joint with R. Jiménez-Rodríguez (U. Salamanca). \emph{Energy Economics}, (2017), \textbf{64}, 24--30.

\item \textbf{``A new look at oil price pass-through into inflation: Evidence from disaggregated European data.''} Joint with R. Jiménez-Rodríguez (U. Salamanca), P. Poncela (European Commission), and E. Senra (U. Alcalá). \emph{Economia Politica: Journal of Analytical and Institutional Economics}, (2017), \textbf{34(1)}, 55--82.

\item \textbf{``The deflationary effect of oil prices in the euro area.''} Joint with A. Barge-Gil (U. Complutense de Madrid), and M. Jerez (U. Complutense de Madrid). \emph{Energy Economics}, (2016), \textbf{56}, 389--397.

\item \textbf{``Oil Prices and Inflation in the Euro Area and its Main Countries: Germany, France, Italy and Spain.''} Joint with P. Poncela (U. Autónoma de Madrid) and E. Senra (U. Alcalá). \emph{FUNCAS Working papers series}, (2012), \textbf{701}.

\item \textbf{``Do we see the effects of oil variations in official statistics price data?''} Joint with P. Poncela (U. Autónoma de Madrid), and E. Senra (U. Alcalá). \emph{Boletín de Estadística e Investigación Operativa}, (2011), \textbf{27}, 29--41.

\item \textbf{``El diferencial de inflación en los servicios entre España y la euro área.''} Joint with E. Carluccio (U. Carlos III de Madrid). \emph{Papeles de Economía Española}, (2009), \textbf{120}, 69--89.

\item \textbf{``Mercado de crédito 1990-1999. La factura de cobro del financiamiento.''} Joint with J. Espitia (CGR Colombia), and J. Villamizar (CGR Colombia). \emph{Gestión Fiscal}, (2000), \textbf{8}, 6--33.
\\

\noindent
\section{Work in progress or submitted}

\item \textbf{``Time-varying relationship between oil price changes and exchange rates.''} Joint with R. Jiménez-Rodríguez (U. Salamanca).

\item \textbf{``Oil price shocks and inflation across euro area countries.''} Joint with A. Barge-Gil (U. Complutense de Madrid), and M. Jerez (U. Complutense de Madrid).
\\
\end{enumerate}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\section{Professional Activities} 

\begin{tabular}{rl{-2cm}}

2002--2014 &  \textbf{Economic Analyst}, Madrid, Spain\\
\vspace{5pt}& Universidad Carlos III de Madrid, Department of Economics--Statistics.\\

2000 & \textbf{Economic Analyst}, Bogotá, Colombia\\
\vspace{5pt}& CGR, Dirección de Estudios Macroeconómicos.\\

1998--1999 & \textbf{Project Manager}, Bogotá, Colombia\\
\vspace{5pt}& Universidad Nacional de Colombia, Department of Economics.\\

1995--1998 & \textbf{Research Assistant}, Bogotá, Colombia\\
\vspace{5pt}& Universidad Nacional de Colombia, Department of Economics.}\\

1995--1999 & \textbf{Lecturer}, Bogotá, Colombia\\
\vspace{5pt}& Economics (B.A. and M.A.), Universidad Nacional de Colombia.\\

\end{tabular}
\vspace{10pt}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\section{Conference presentations} 

\begin{itemize}

\item \textbf{``Oil price pass-through along the price chain in the euro area.''} 12th Conference of the Spanish Association for Energy Economics, Salamanca, Spain, 2017.

\item \textbf{``A new look at oil price pass-through into inflation: Evidence from disaggregated European data.''} 7th Research Workshop on Energy Markets, Valencia, Spain, 2016.

\item \textbf{``The deflationary effect of oil prices in the euro area.''} Energy Economics Iberian Conference, Lisboa, Portugal, 2016.

\item \textbf{``Oil prices and inflation in the euro area and its main countries: Germany, France, Italy and Spain.''} 32nd International Symposium on Forecasting, Boston, U.S.A., 2012.

\item \textbf{``Factores comunes en los precios de las materias primas e inflación en la euro área y sus principales economías.''} XXXIII Congreso Nacional de Estadística e Investigación Operativa, Madrid, Spain, 2012.

\item \textbf{``Oil prices and inflation in the euro area and its main countries: Germany, France, Italy and Spain.''} Association of Southern European Economic Theorists, Universidad de Évora, Portugal, 2011.

\item \textbf{``Oil Prices and inflation in the euro area and main partners: Spain, Italy, France and Germany.``} Euro-Mediterranean Competitiveness Meeting, Universidad de Alcalá, Spain, 2011.

\end{itemize}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\section{Honors} 

\begin{tabular}{rl}

2016   & \textbf{University of Salamanca}\\
& Outstanding Doctorate Award\\

2000	 & \textbf{Santander Bank - University of Alcalá}\\
&  Scholarship\\

1995 & \textbf{Inter-American Development Bank}\\
& Invited to the Youth and Growth Forum, Jerusalem, Israel.

\end{tabular}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\section{Computer skills} 

\begin{tabular}{rl}
\textbf{\textsf{R}} programming language, {\LaTeX}, SCA, Microsoft Office, \textsc{MATLAB}, \textsc{Eviews}\\
&
\end{tabular}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\section{Languages} 

\begin{tabular}{rl}
Spanish (native), English (Intermediate, B2)
\end{tabular}

% \clearpage
% 
% 
% \textbf{Reference \#1}
% 
% \textbf{Miguel Jerez Méndez}\\
% Department of Economics\\
% Faculty of Economics and Business\\
% University Complutense de Madrid\\
% Campus de Somosaguas\\
% E-28223 Pozuelo de Alarcón, Madrid\\
% Tfno.: +34 913 94 24 32\\
% e-mail: mjerezme@ucm.es\\
% \\
% \\
% 
% \textbf{Reference \#2}
% 
% \textbf{Rebeca Jiménez-Rodríguez}\\
% Department of Economics\\
% IME, Faculty of Economics and Business\\
% University of Salamanca\\
% Building: FES, Campus Miguel de Unamuno, s/n\\
% E-37007 Salamanca\\
% Tfno.: +34 923 29 45 00 ext. 4668 or 1967\\
% Fax: +34 923 29 46 76\\
% e-mail: rebeca.jimenez@usal.es
\end{document}
